- name: Deploy Calculator App
  hosts: local
  tasks:
    - name: Pull latest image
      shell: /usr/local/bin/docker pull yuvraj12345678/calculator-app:latest

    - name: Stop existing container
      shell: /usr/local/bin/docker stop calculator-app || true

    - name: Remove existing container
      shell: /usr/local/bin/docker rm calculator-app || true

    - name: Run new container
      shell: >
        /usr/local/bin/docker run -d --name calculator-app 
        -p 8080:8080 
        -v /var/log/calculator:/logs 
        yuvraj12345678/calculator-app:latest