input {
  file {
    path => "/logs/calculator-app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}
filter {
  # This part turns your text logs into searchable data
  if [message] =~ "Calculating" {
    mutate { add_tag => [ "calculation_event" ] }
  }
}
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "calculator-logs"
  }
}

